name: Compile Latest Blender iPad App
on:
push:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-14
    steps:
      - name: Checkout Blender Source
        uses: actions/checkout@v4
        with:
        repository: 'blender/blender'
          ref: ios
          lfs: true

      - name: Install Development Tools
        run: |
          brew install cmake ninja

      - name: Setup Workspace Directory
        run: |
          cd.. 
          mkdir -p lib/darwin_arm64

      - name: Fetch Offical Apple iPad Libraries
        run: |
          python3 ./build_files/utils/make_update.py --use-ios-libraries

      - name: Configure CMake for iOS App
        run: |
          mkdir build_ios
          cd build_ios
          cmake -G Ninja \
          -DCMAKE_SYSTEM_NAME=iOS \
          -DCMAKE_OSX_SYSROOT=iphoneos \
          -DCMAKE_BUILD_TYPE=RELEASE \
          ../blender

      - name: Compile Code
        run: |
          cd build_ios
          ninja

      - name: Package Into IPA Payload
        run: | 
          mkdir -p Payload 
          cp -r build_ios/bin/Blender.app Payload/
          zip -r Blender_Latest.ipa Payload

      - name: Upload Finished IPA
        uses: actions/upload-artifact@v4
        with:
          name: Blender-iPad-Latest-Build
          path: Blender_Latest.ipa
